package com.mtech.recycler.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.mtech.recycler.dto.ItemDto;
import com.mtech.recycler.helper.Utilities;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "RecycleRequest")
public class RecycleRequest {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String returnCode;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private BigDecimal totalPrice;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = Utilities.ItemListConverter.class)
    private List<ItemDto> dbItems;

    @DynamoDBAttribute
    private String collectionStatus;

    @DynamoDBAttribute
    private String promoCode;

    @DynamoDBAttribute
    private String contactPerson;

    @DynamoDBAttribute
    private String contactNumber;

    @DynamoDBAttribute
    private String collectionDate;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @DynamoDBDocument
    public static class DbItem {
        @DynamoDBAttribute
        private String category;

        @DynamoDBAttribute
        private Double quantity;

        @DynamoDBAttribute
        private BigDecimal unitPrice;

        @DynamoDBAttribute
        private BigDecimal subTotalPrice;

        @DynamoDBAttribute
        private String description;
    }
}