package com.mtech.recycler.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.mtech.recycler.helper.Utilities;
import lombok.*;

import java.math.BigDecimal;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "RecycleItem")
public class RecycleItem {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String returnCode;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private BigDecimal totalPrice;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = Utilities.ItemListConverter.class)
    private List<com.mtech.recycler.model.Item> dbItems;

    @DynamoDBAttribute
    private String collectionStatus;

    @DynamoDBAttribute
    private String promoCode;

    @DynamoDBAttribute
    private String contactPerson;

    @DynamoDBAttribute
    private String contactNumber;

    @DynamoDBAttribute
    private String collectionDate;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @DynamoDBDocument
    public static class DbItem {
        @DynamoDBAttribute
        private String category;

        @DynamoDBAttribute
        private Double quantity;

        @DynamoDBAttribute
        private BigDecimal unitPrice;

        @DynamoDBAttribute
        private BigDecimal subTotalPrice;
    }
}